apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YulianBortsov/ort_project_yulian_ziv.git'
    targetRevision: HEAD
    path: helm/ort_proj_netflix
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: netflix-catalog-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true